repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
    stages: [commit]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        stages: [commit]

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        stages: [commit]
        exclude: ^tests/
