version: '3'
services:
  bert-deployment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/code/config/:rw
      - ../results:/code/results/:rw
      - ../data:/code/data/:rw
    command: "uvicorn api:app --port 8000"
    ports:
      - "127.0.0.1:8888:8000"